title: Philipp Benner
description: Researcher at <a href="https://www.bam.de">BAM</a>. <a href="https://github.com/pbenner">[Github]</a>, <a href="https://twitter.com/PhilippBenner2">[Twitter]</a>, <a href= "mailto:philipp.benner@bÃ¤m.de">[Email]</a>
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
